spring:
  application:
    name: mind-gateway
  cloud:
    nacos:
      server-addr: 54.162.69.70:8848
      discovery:
        ip: 127.0.0.1
    gateway:
      routes:
        - id: mind-user # 路由标示，必须唯一
          uri: lb://mind-user # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/** # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: mind-podcast # 路由标示，必须唯一
          uri: lb://mind-podcast # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/podcast/** # 路径断言，判断路径是否是以/user开头，如果是则符合
  redis:
    database: 1
    host: zeabur-gcp-asia-east1-1.clusters.zeabur.com
    port: 30763
    timeout: 5000
    password: B1FU7V9z8L34
#  zipkin:
#    base-url: localhost:9412
#    service:
#      name: mind-gateway
#    enabled: true
#    sleuth:
#      sampler:
#        probability: 1.0
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.web.reactive: debug